---
- name: Deploy Python Artifact
  hosts: pythonservers
  become: yes

  tasks:

    - name: Create application directory
      file:
        path: /opt/python-app
        state: directory

    - name: Copy artifact
      copy:
        src: /python-works/python-app.tar.gz
        dest: /opt/python-app/python-app.tar.gz

    - name: Extract artifact
      unarchive:
        src: /opt/python-app/python-app.tar.gz
        dest: /opt/python-app
        remote_src: yes

    - name: Execute application
      command: python3 /opt/python-app/app.py

    - name: Verify file exists
      stat:
        path: /tmp/system_info.txt
      register: result

    - name: Show status
      debug:
        var: result.stat.exists
